# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FBG_advanced_start.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FBG_advanced_start.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


'''
need to be added:
        VALIDATION BETWEEN CHOSEN PARAMETERS
 passing parameters
        bragg spacing
        order
        length 
        chosen height
given paramters from fiber
        setting min and max for inscription legnth(height)
        index of refraction


'''

from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtSerialPort import QSerialPort
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QIODevice
import serial.tools.list_ports
from pylablib.devices import Thorlabs
from PyQt5.QtGui import QPixmap

class Ui_Form(object):
    def __init__(self, n, minH, maxH):
        self.n = n
        self.minH = minH
        self.maxH = maxH
        print(self.n)
        print(self.minH)
        print(self.maxH)

    def clicked(self, FBG_advanced_start_info, MainWindow_info, FBG_imaging_info, FBG_etching_info, FBG_end_info):
        self.window = QtWidgets.QWidget() #type
        self.ui = FBG_imaging_info(self.n, self.minH, self.maxH, self.bs,self.period, self.height, self.power, self.order) #class name
        self.ui.setupUi(self.window, MainWindow_info, FBG_etching_info, FBG_end_info)
        self.window.show() # opens this new window 
        FBG_advanced_start_info.hide() # hides this window 


    def setupUi(self, Form, MainWindow, FBG_imaging, FBG_etching, FBG_end):
        Form.setObjectName("Form")
        Form.resize(1121, 952)
        Form.setStyleSheet("QWidget{\n"
"\n"
"background-color:rgb(23, 17, 57)\n"
"}")
        self.horizontalScrollBar = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(180, 220, 201, 31))
        self.horizontalScrollBar.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 1px solid #3498db;\n"
"    background: #3498db;\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3498db;\n"
"    min-width: 20px;\n"
"}")
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalScrollBar_3 = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar_3.setGeometry(QtCore.QRect(180, 360, 201, 31))
        self.horizontalScrollBar_3.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 1px solid #3498db;\n"
"    background: #3498db;\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3498db;\n"
"    min-width: 20px;\n"
"}")
        self.horizontalScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_3.setObjectName("horizontalScrollBar_3")
        self.pushButton = QtWidgets.QPushButton(Form, clicked = lambda: self.clicked(Form, MainWindow, FBG_imaging, FBG_etching, FBG_end))
        self.pushButton.setGeometry(QtCore.QRect(440, 860, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #3498db; /* Blue background color */\n"
"    color: #ffffff; /* White text color */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    width: 100px; /* Set a specific width */\n"
"    height: 40px; /* Set a specific height */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(240, 30, 601, 71))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color:rgb(255, 0, 127)\n"
"}")
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(380, 210, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(380, 350, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.heightLabel = QtWidgets.QLabel(Form)
        self.heightLabel.setGeometry(QtCore.QRect(250, 400, 61, 16))
        self.heightLabel.setStyleSheet("QLabel{\n"
"\n"
" color: white;\n"
"}")
        self.heightLabel.setObjectName("heightLabel")
        self.spacingLabel = QtWidgets.QLabel(Form)
        self.spacingLabel.setGeometry(QtCore.QRect(250, 260, 61, 16))
        self.spacingLabel.setStyleSheet("QLabel{\n"
"\n"
" color: white;\n"
"}")
        self.spacingLabel.setObjectName("spacingLabel")
        self.powerLabel = QtWidgets.QLabel(Form)
        self.powerLabel.setGeometry(QtCore.QRect(250, 630, 61, 16))
        self.powerLabel.setStyleSheet("QLabel{\n"
"\n"
" color: white;\n"
"}")
        self.powerLabel.setObjectName("powerLabel")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(380, 570, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.horizontalScrollBar_4 = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar_4.setGeometry(QtCore.QRect(180, 590, 201, 31))
        self.horizontalScrollBar_4.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 1px solid #3498db;\n"
"    background: #3498db;\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3498db;\n"
"    min-width: 20px;\n"
"}")
        self.horizontalScrollBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_4.setObjectName("horizontalScrollBar_4")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(260, 780, 61, 16))
        self.label_6.setStyleSheet("QLabel{\n"
"\n"
" color: white;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(380, 730, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.horizontalScrollBar_5 = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar_5.setGeometry(QtCore.QRect(180, 740, 201, 31))
        self.horizontalScrollBar_5.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 1px solid #3498db;\n"
"    background: #3498db;\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3498db;\n"
"    min-width: 20px;\n"
"}")
        self.horizontalScrollBar_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_5.setObjectName("horizontalScrollBar_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(640, 140, 261, 171))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("braggspacing.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(620, 330, 291, 111))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("height.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(630, 550, 291, 111))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("power.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(120, 210, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_6.setFont(font)
        self.plainTextEdit_6.setStyleSheet("QPlainTextEdit{\n"
"\n"
"color:white;\n"
"}")
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(120, 350, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_8.setFont(font)
        self.plainTextEdit_8.setStyleSheet("QPlainTextEdit{\n"
"\n"
"color:white;\n"
"}")
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_9.setGeometry(QtCore.QRect(120, 580, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_9.setFont(font)
        self.plainTextEdit_9.setStyleSheet("QPlainTextEdit{\n"
"\n"
"color:white;\n"
"}")
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(90, 730, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_10.setFont(font)
        self.plainTextEdit_10.setStyleSheet("QPlainTextEdit{\n"
"\n"
"color:white;\n"
"}")
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(590, 680, 471, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("order.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(110, 870, 301, 61))
        self.textEdit_4.setStyleSheet("QTextEdit{\n"
"color: white;\n"
"}")
        self.textEdit_4.setObjectName("textEdit_4")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(380, 460, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_7.setFont(font)
        self.plainTextEdit_7.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.horizontalScrollBar_6 = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar_6.setGeometry(QtCore.QRect(180, 470, 201, 31))
        self.horizontalScrollBar_6.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 1px solid #3498db;\n"
"    background: #3498db;\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3498db;\n"
"    min-width: 20px;\n"
"}")
        self.horizontalScrollBar_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_6.setObjectName("horizontalScrollBar_6")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(610, 430, 311, 131))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("length.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.periodLabel = QtWidgets.QLabel(Form)
        self.periodLabel.setGeometry(QtCore.QRect(250, 510, 61, 16))
        self.periodLabel.setStyleSheet("QLabel{\n"
"\n"
" color: white;\n"
"}")
        self.periodLabel.setObjectName("periodLabel")
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_11.setGeometry(QtCore.QRect(90, 460, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_11.setFont(font)
        self.plainTextEdit_11.setStyleSheet("QPlainTextEdit{\n"
"\n"
"color:white;\n"
"}")
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Ready to continue?"))
        self.label_2.setText(_translate("Form", "Please select your parameters!"))
        self.plainTextEdit.setPlainText(_translate("Form", "Bragg Wavelngth\n"
"Limits: 1300-1550 nm"))
        self.plainTextEdit_3.setPlainText(_translate("Form", "Gratting Height\n"
"Limits:  um"))
        self.heightLabel.setText(_translate("Form", "TextLabel"))
        self.spacingLabel.setText(_translate("Form", "TextLabel"))
        self.powerLabel.setText(_translate("Form", "TextLabel"))
        self.plainTextEdit_4.setPlainText(_translate("Form", "Power Attenuation\n"
"Limits: 4-8 OD"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.plainTextEdit_5.setPlainText(_translate("Form", "Order\n"
"Limits: 1-3"))
        self.plainTextEdit_6.setPlainText(_translate("Form", "nm"))
        self.plainTextEdit_8.setPlainText(_translate("Form", "um"))
        self.plainTextEdit_9.setPlainText(_translate("Form", "OD"))
        self.plainTextEdit_10.setPlainText(_translate("Form", "Unitless"))
        self.textEdit_4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please be patient when you select your option. Clicking twice will lead to the program crashing.</p></body></html>"))
        self.plainTextEdit_7.setPlainText(_translate("Form", "Periods\n"
"Limits: 5000-10,000"))
        self.periodLabel.setText(_translate("Form", "TextLabel"))
        self.plainTextEdit_11.setPlainText(_translate("Form", "Unitless"))



#################################this is where the values of thesliders will be displayed#########################################
        self.horizontalScrollBar.valueChanged.connect(self.spaceingValue)
        self.horizontalScrollBar_6.valueChanged.connect(self.periodValue)
        self.horizontalScrollBar_3.valueChanged.connect(self.heightValue)
        self.horizontalScrollBar_4.valueChanged.connect(self.powerValue)
        self.horizontalScrollBar_5.valueChanged.connect(self.orderValue)

### we need to set the min and max based off what fibers are selected###
#SPACING VALUE hard coded

        self.horizontalScrollBar.setMaximum(1550)
        self.horizontalScrollBar.setMinimum(1300)
#ORDER
        self.horizontalScrollBar_6.setMaximum(10000)
        self.horizontalScrollBar_6.setMinimum(500)
                

#HEIGHT - user selection but hard coded
        self.horizontalScrollBar_3.setMaximum(self.maxH)
        self.horizontalScrollBar_3.setMinimum(self.minH)
#POWER NOT REALLY APART OF THIS PROJECT YET- THERE WILL BE ONE SOLID WHEEL AND ONE VARIABLE, SOLID STARTS AT 4od
        self.horizontalScrollBar_4.setMaximum(8)
        self.horizontalScrollBar_4.setMinimum(4)

#ORDER
        self.horizontalScrollBar_5.setMaximum(4)
        self.horizontalScrollBar_5.setMinimum(1)
        

    def spaceingValue (self, value):
        self.spacingLabel.setText(str(value))
        self.bs = value #save user value for spacing


    def heightValue (self, value):
        self.heightLabel.setText(str(value))
        self.height = value 

    def periodValue (self, value):
        self.periodLabel.setText(str(value))
        self.period  = value 

    def powerValue (self, value):
        self.powerLabel.setText(str(value))
        self.power = value

    def orderValue (self, value):
        self.label_6.setText(str(value))
        self.order = value

########################################################################################################################################



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
