# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FBG_fiber.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.




'''

need to be added:

    the different single mode fibers person could edit, maybe a description for it

    
    diameter cladding/core- sets inscription hieght max
    diameter core- sets inscription height min
    index of refraction 

'''


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def clicked_continue(self, FBG_fiber_info, MainWindow_info, FBG_who_info, basic_start_info, advanced_start_info, FBG_imaging_info, FBG_etching_info, FBG_end_info): #added MainWindow_info
        
        combo = self.comboBox.currentText()
        #if index 0 or 1 set n = blank and inscription height min and max = to blank
        if combo == "OS1":
            n = 1.466
            minH = 8
            maxH = 118
            
        if combo == "OS2":
            n = 1.466
            minH = 8
            maxH = 118
            
        self.window = QtWidgets.QWidget() #type
        self.ui = FBG_who_info(n, minH, maxH) #class name
        #self.ui is this FBG_who, now include other info things from above
        self.ui.setupUi(self.window, MainWindow_info, basic_start_info, advanced_start_info, FBG_imaging_info, FBG_etching_info, FBG_end_info) #added MainWindow_info
        self.window.show() # opens this new window 
        FBG_fiber_info.hide() # hides this window


    def setupUi(self, Form, MainWindow, FBG_who, basic_start, advanced_start, FBG_imaging, FBG_etching, FBG_end):
        Form.setObjectName("Form")
        Form.resize(1081, 871)
        Form.setStyleSheet("QWidget{\n"
"\n"
"background-color:rgb(23, 17, 57)\n"
"}")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(300, 290, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{\n"
"   color: white; /* Blue background color */\n"
"     border: 3px solid #3498db;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 140, 981, 61))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color:rgb(255, 0, 127)\n"
"}")
        self.label.setObjectName("label")


        
    ################################################

        self.pushButton = QtWidgets.QPushButton(Form, clicked = lambda: self.clicked_continue(Form, MainWindow, FBG_who, basic_start, advanced_start, FBG_imaging, FBG_etching, FBG_end))
        
    
    ################################################



        self.pushButton.setGeometry(QtCore.QRect(330, 410, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #3498db; /* Blue background color */\n"
"    color: #ffffff; /* White text color */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    width: 100px; /* Set a specific width */\n"
"    height: 40px; /* Set a specific height */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(680, 250, 161, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "OS1"))
        self.comboBox.setItemText(1, _translate("Form", "OS2"))
        self.label.setText(_translate("Form", "What kind of fiber are we working with?"))
        self.pushButton.setText(_translate("Form", "Ready to continue?"))
        self.plainTextEdit.setPlainText(_translate("Form", "There are two types of single mode fibers that we will aim to etch. OS1, which is meant for indoor use and OS2 which is meant for outdoor use!")) 
    



    ################################################

    
'''
    def comboValues(self):
        combo = self.comboBox.currentText()
        #if index 0 or 1 set n = blank and inscription height min and max = to blank
        if combo == "OS1":
            self.n = 0
            self.minHeight = 0
            self.maxHeight = 1
            print(self.n)
        if combo == "OS2":
            self.n = 5
            self.minHeight = 1
            self.maxHeight = 2
            print(self.n)

'''

    ################################################

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
