# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FBG_end.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


'''
need to add:
    PARAMETERS


'''



from PyQt5.QtSerialPort import QSerialPort
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QIODevice
import serial.tools.list_ports
from pylablib.devices import Thorlabs
import os


class Ui_Form(object):
    def __init__(self, n, minH, maxH, bs, period, height, power, order):
        self.n = n
        self.minH = minH
        self.maxH = maxH
        self.bs =bs 
        self.period=period
        self.height = height
        self.power = power
        self.order = order
        print(self.n)
        print(self.minH)
        print(self.maxH)
        print(self.bs)
        print(self.period)
        print(self.height)
        print(self.power)
        print(self.order)
        
    def saveFile(self): #add all imported variables?
        print("file saved")
        FileName = open("etchingData.txt", mode='w')
        FileName.write("This is your saved etching parameters! This code will be updated with every new etch" + "\n")

#input variable
#note it has to be string
        FileName.write("Bragg Spacing: " + str(self.bs) + "\n")
        FileName.write("Gratings Height: " + str(self.height) + "\n")
        FileName.write("Laser Power Attenuation: " + str(self.power) + "\n")
        FileName.write("Periods: " + str(self.power) + "\n")
        FileName.write("Grating Order: " + str(self.order) + "\n")
        FileName.close()





    def clicked(self, FBG_end_info, MainWindow_info):
        MainWindow_info.show() 
        FBG_end_info.hide() # hides this window

    def setupUi(self, Form, MainWindow):#, FBG_etching, FBG_end):
        Form.setObjectName("Form")
        Form.resize(1079, 872)
        Form.setStyleSheet("QWidget{\n"
"\n"
"background-color:rgb(23, 17, 57)\n"
"}")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(390, 310, 291, 101))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        font.setPointSize(33)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color:rgb(255, 0, 127)\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form, clicked = lambda: self.clicked(Form, MainWindow))
        self.pushButton.setGeometry(QtCore.QRect(230, 430, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #3498db; /* Blue background color */\n"
"    color: #ffffff; /* White text color */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    width: 100px; /* Set a specific width */\n"
"    height: 40px; /* Set a specific height */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form, clicked = lambda: self.saveFile())
        self.pushButton_2.setGeometry(QtCore.QRect(580, 430, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #3498db; /* Blue background color */\n"
"    color: #ffffff; /* White text color */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    width: 100px; /* Set a specific width */\n"
"    height: 40px; /* Set a specific height */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Thank you!"))
        self.pushButton.setText(_translate("Form", "Return to Home"))
        self.pushButton_2.setText(_translate("Form", "Save Results"))

  


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
