# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FBG_basic_start.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

'''
need to added:

        the three types of gratings a person could choose from

 passing parameters
        bragg spacing
        order
        length 
        chosen height
given
        index of refract

        (self.n, self.minH, self.maxH, self.bs, self.length, self.height, self.power, self.order) this needs to be added to the self.ui = FBG_unaging infor after the button clicks have been addressed

        the button clicks need to corrospond to their etching patterns

'''





from PyQt5.QtSerialPort import QSerialPort
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QIODevice
import serial.tools.list_ports
from pylablib.devices import Thorlabs


class Ui_Form(object):
    def __init__(self, n, minH, maxH):
        self.n = n
        self.minH = minH
        self.maxH = maxH
        print(self.n)
        print(self.minH)
        print(self.maxH)

    def clicked1(self, FBG_basic_start_info, MainWindow_info, FBG_imaging_info, FBG_etching_info, FBG_end_info):

        self.bs=1400
        self.height=50
        self.power=4
        self.order=1
        self.period=25

        self.window = QtWidgets.QWidget() #type
        self.ui = FBG_imaging_info(self.n, self.minH, self.maxH, self.bs, self.period, self.height, self.power, self.order) #class name
        self.ui.setupUi(self.window, MainWindow_info, FBG_etching_info, FBG_end_info)
        self.window.show() # opens this new window 
        FBG_basic_start_info.hide() # hides this window

    def clicked2(self, FBG_basic_start_info, MainWindow_info, FBG_imaging_info, FBG_etching_info, FBG_end_info):

        self.bs=1450
        self.height=50
        self.power=4
        self.order=2
        self.period=25

        self.window = QtWidgets.QWidget() #type
        self.ui = FBG_imaging_info(self.n, self.minH, self.maxH, self.bs, self.period, self.height, self.power, self.order) #class name
        self.ui.setupUi(self.window, MainWindow_info, FBG_etching_info, FBG_end_info)
        self.window.show() # opens this new window 
        FBG_basic_start_info.hide() # hides this window

    def clicked3(self, FBG_basic_start_info, MainWindow_info, FBG_imaging_info, FBG_etching_info, FBG_end_info):

        self.bs=1500
        self.height=50
        self.power=4
        self.order=3
        self.period=25

        self.window = QtWidgets.QWidget() #type
        self.ui = FBG_imaging_info(self.n, self.minH, self.maxH, self.bs, self.period, self.height, self.power, self.order) #class name
        self.ui.setupUi(self.window, MainWindow_info, FBG_etching_info, FBG_end_info)
        self.window.show() # opens this new window 
        FBG_basic_start_info.hide() # hides this window

    def setupUi(self, Form, MainWindow, FBG_imaging, FBG_etching, FBG_end):
        Form.setObjectName("Form")
        Form.resize(1074, 871)
        Form.setStyleSheet("QWidget{\n"
"\n"
"background-color:rgb(23, 17, 57)\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Form, clicked = lambda: self.clicked1(Form, MainWindow, FBG_imaging, FBG_etching, FBG_end))
        self.pushButton.setGeometry(QtCore.QRect(100, 400, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #3498db; /* Blue background color */\n"
"    color: #ffffff; /* White text color */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    width: 100px; /* Set a specific width */\n"
"    height: 40px; /* Set a specific height */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form, clicked = lambda: self.clicked2(Form, MainWindow, FBG_imaging, FBG_etching, FBG_end))
        self.pushButton_2.setGeometry(QtCore.QRect(100, 490, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #3498db; /* Blue background color */\n"
"    color: #ffffff; /* White text color */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    width: 100px; /* Set a specific width */\n"
"    height: 40px; /* Set a specific height */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form, clicked = lambda: self.clicked3(Form, MainWindow, FBG_imaging, FBG_etching, FBG_end))
        self.pushButton_3.setGeometry(QtCore.QRect(100, 310, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #3498db; /* Blue background color */\n"
"    color: #ffffff; /* White text color */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    width: 100px; /* Set a specific width */\n"
"    height: 40px; /* Set a specific height */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(280, 290, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(300, 70, 451, 61))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        font.setPointSize(32)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color:rgb(255, 0, 127)\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(540, 150, 271, 111))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("braggspacing.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(540, 380, 281, 121))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("length.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(520, 260, 311, 121))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("height.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(150, 640, 671, 191))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("order.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(540, 510, 281, 121))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("power.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(160, 210, 301, 61))
        self.textEdit_4.setStyleSheet("QTextEdit{\n"
"color: white;\n"
"}")
        self.textEdit_4.setObjectName("textEdit_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(810, 210, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(810, 320, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(810, 440, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(810, 580, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(280, 380, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(280, 470, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"}")
        self.textEdit_3.setObjectName("textEdit_3")


        self.bs=0
        self.height=0
        self.power=0
        self.order=0
        self.period=0

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)






    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Option 2"))
        self.pushButton_2.setText(_translate("Form", "Option 3"))
        self.pushButton_3.setText(_translate("Form", "Option 1 "))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">    Bragg Wavelength: 1400nm </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">   Height of Grating: 50um </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">             Periods: 25 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">               Order: 1 </span></p></body></html>"))
        self.label_2.setText(_translate("Form", "Choose an option!"))
        self.textEdit_4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please be patient when you select your option. Clicking twice will lead to the program crashing.</p></body></html>"))
        self.plainTextEdit.setPlainText(_translate("Form", "Bragg Wavelength"))
        self.plainTextEdit_2.setPlainText(_translate("Form", "Grating Height"))
        self.plainTextEdit_3.setPlainText(_translate("Form", "Periods"))
        self.plainTextEdit_4.setPlainText(_translate("Form", " Power Attenuation"))
        self.textEdit_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">   Bragg Wavelength: 1450nm</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">  Height of Grating: 50um</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">            Periods: 25</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">              Order: 2</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">   Bragg Wavelength: 1500</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">  Height of Grating: 50um</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">            Periods: 25</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">              Order: 3</span></p></body></html>"))







if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
