# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FBG_who.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

'''
need to add;
    fix textbox thingies look weird

'''


from PyQt5.QtSerialPort import QSerialPort
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QIODevice
import serial.tools.list_ports
from pylablib.devices import Thorlabs


class Ui_Form(object):
    def __init__(self, n, minH, maxH):
        self.n = n
        self.minH = minH
        self.maxH = maxH
        print(self.n)
        print(self.minH)
        print(self.maxH)


    def basic_clicked(self, FBG_who_info, MainWindow_info, FBG_basic_start_info, FBG_imaging_info, FBG_etching_info, FBG_end_info):
    
        self.window = QtWidgets.QWidget() #type
        self.ui = FBG_basic_start_info(self.n, self.minH, self.maxH) #class name
        self.ui.setupUi(self.window, MainWindow_info, FBG_imaging_info, FBG_etching_info, FBG_end_info)
        self.window.show() # opens this new window 
        FBG_who_info.hide() # hides this window

    def advanced_clicked(self, FBG_who_info, MainWindow_info, FBG_advanced_start_info, FBG_imaging_info, FBG_etching_info, FBG_end_info):
           
        self.window = QtWidgets.QWidget() #type
        self.ui = FBG_advanced_start_info(self.n, self.minH, self.maxH) #class name
        self.ui.setupUi(self.window, MainWindow_info, FBG_imaging_info, FBG_etching_info, FBG_end_info)
        self.window.show() # opens this new window 
        FBG_who_info.hide() # hides this window

        
    def setupUi(self, Form, MainWindow, basic_start, advanced_start, FBG_imaging, FBG_etching, FBG_end):
        Form.setObjectName("Form")
        Form.resize(1080, 869)
        Form.setStyleSheet("QWidget{\n"
"\n"
"background-color:rgb(23, 17, 57)\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Form, clicked = lambda: self.advanced_clicked(Form, MainWindow, advanced_start, FBG_imaging, FBG_etching, FBG_end))
        self.pushButton.setGeometry(QtCore.QRect(260, 320, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #3498db; /* Blue background color */\n"
"    color: #ffffff; /* White text color */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    width: 100px; /* Set a specific width */\n"
"    height: 40px; /* Set a specific height */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form, clicked = lambda: self.basic_clicked(Form, MainWindow, basic_start, FBG_imaging, FBG_etching, FBG_end))
        self.pushButton_2.setGeometry(QtCore.QRect(660, 320, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #3498db; /* Blue background color */\n"
"    color: #ffffff; /* White text color */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    width: 100px; /* Set a specific width */\n"
"    height: 40px; /* Set a specific height */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(180, 430, 361, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(600, 430, 321, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"}")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(190, 130, 711, 101))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        font.setPointSize(32)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color:rgb(255, 0, 127)\n"
"}")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Advanced"))
        self.pushButton_2.setText(_translate("Form", "Basic"))
        self.plainTextEdit.setPlainText(_translate("Form", "The advanced path will allow you to choose specific gratings using the following parameters: Bragg Spacing, Length, Height, Power, and Order."))
        self.plainTextEdit_2.setPlainText(_translate("Form", "The basic path will allow you to choose between three preset gratings options."))
        self.label_2.setText(_translate("Form", "What\'s your experience level?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
